### ISSUE TITLE
部分内容未翻译

### ISSUE THREAD

**Issue by wegood9** [fgc0109/TheLongDarkSaveEditorTranslate#1]
部分物品、MAP、坐标、模式、地区未翻译。
另：希望能换个字体，这个字体在Windows默认渲染下瞎眼

**Comment by wegood9** [comment]
看了下源码，是故意不翻译？

**Comment by fgc0109** [comment]
翻译正在慢慢补充,有好的建议可以一起翻译
现有的绝大部分都是从旧版本中检索出来翻译好的词条.我自己在慢慢补充

字体这个,我不太清楚怎么在不反编译的情况下更换字体额

**Comment by wegood9** [comment]
翻译从官方文本/贴吧搞就好了。
至于字体，我也不太清楚怎么办，等大佬来吧。

**Comment by fgc0109** [comment]
有道理
我抽空把所有的未翻译物品都用改一份出来,然后看看官方翻译的中文是什么,然后我改一下翻译文本.

**Comment by fgc0109** [comment]
怼狼怼熊提供了翻译文本,已经补充了缺少的翻译
